name: Gelu_Suggest
author: Gelumaxon
main: gelumaxon\GeluSuggest\Main
api: 4.0.0
version: 1.4
commands: 
 suggest:
  description: Suggestion plugin with webhook
  permission: suggest.use
permissions:
 suggest.use:
  default: true
