# Put the webhook code below:
webhook: "https://discord.com/api/webhooks/987522776782995476/fCs_HvPhKs61uB4b49XQSLgQXAwJKkBOxydU7EXVlw66SzJtWuKuGfVeRWtrocsUn47q"
# Plugin made by </Gelumaxon>#2886, do not sell this plugin
